# Generated by Django 2.2.11 on 2020-03-28 17:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pack_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place_name', models.CharField(max_length=200)),
                ('place_address', models.CharField(max_length=200)),
                ('place_category', models.CharField(max_length=20)),
                ('place_distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trip_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pack_days', models.IntegerField()),
                ('trip', jsonfield.fields.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='users_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mo_no', models.IntegerField()),
            ],
        ),
    ]
