# Generated by Django 2.2.11 on 2020-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_trip_details_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_details',
            name='radius',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
    ]
